name: Sora V2 Stock Checker (hourly)

on:
  schedule:
    - cron: "0 * * * *"   # 1x pro Stunde zur vollen Stunde (UTC)
  workflow_dispatch:      # optional: manuell starten

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run checker once
        env:
          RUN_ONCE: "1"
        run: python Main.py   # falls deine Datei klein geschrieben ist: python main.py
