name: Sora V2 Stock Checker

on:
  schedule:
    - cron: "*/5 * * * *"   # alle 5 Minuten
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run checker once (no email)
        env:
          RUN_ONCE: "1"
          # Optional: später, wenn gewünscht
          # DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # PRODUCT_URLS: ${{ secrets.PRODUCT_URLS }}
        run: python Main.py   # oder: python main.py  -> je nach Dateiname!
