name: Sora V2 Stock Checker

on:
  schedule:
    - cron: "*/5 * * * *"   # alle 5 Minuten
  workflow_dispatch:        # manuell startbar

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run checker
        run: python Main.py   # <- Achtung: Großes M, wie in deinem Repo!
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
          PRODUCT_URLS: ${{ secrets.PRODUCT_URLS }}   # optional
          CHECK_EVERY_SECONDS: "60"  # beim CI-Lauf: 60s, damit er zügig fertig wird
